name: 'paysim_dbt'
version: '1.0.0'
profile: 'paysim_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  paysim_dbt:
    staging:
      +materialized: view
      +schema: STAGING
    dimensions:
      +materialized: table
      +schema: TRUSTED
    facts:
      +materialized: table
      +schema: TRUSTED
snapshots:
    paysim_dbt:
        dimensions:
          +schema: SNAPSHOTS